### ISSUE TITLE
Use the wikipedia information in Person.csv

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/WikidataLookup#19]
When a Wikipedia information is given already,
use it to get the Q-ids

**Comment by whalekeykeeper** [comment]
It is working for most `person`.
Current issue:
For link `https://en.wikipedia.org/wiki/Fyodor_Dostoyevsky`, the query `
https://en.wikipedia.org/w/api.php?action=query&prop=pageprops&titles=Fyodor_Dostoyevsky&format=json` does not return a response that contains a Wikibase identifier like other links in `Person.csv`.
There must be something wrong, either the way of extracting this name or the way of conducting query entries with Mediawiki's API.

By the way, so far we have only used those links which start with `https://en.wikipedia.org/wiki/`. Because I assume that the Mediawiki API only supports English Wikipedia pages. Will try `https://zh.wikipedia.org/wiki/` soon. But even `https://en.wikipedia.org/wiki/` could work with Mediawiki's API, actually, they still need other approaches because the following part in the link with `zh` is consisting of unreadable letters and digits while the accordingly string is the person's name in `en` links.

**Comment by duncdrum** [comment]
actualy that gibberish is an URL encoded string, i would expect it to work with the API without modification.

**Comment by whalekeykeeper** [comment]
Just a reminder:
some wiki links do not point to the page we need.
For example, for `AG0141`, 'https://zh.wikipedia.org/wiki/%E9%BB%8E%E6%BE%8D' points to a disambiguation page.

**Comment by whalekeykeeper** [comment]
Another reminder, some wiki links are not valid, for example:
https://en.wikipedia.org/wiki/Sergei_yesenin
`Wikipedia does not have an article with this exact name. `

**Comment by whalekeykeeper** [comment]
The total number of Q-identifier that can be extracted from the `Person.csv` directly is:  380

**Comment by duncdrum** [comment]
ok great stuff, please compile a list of invalid wikipedia links and open an issue in the readact repo

**Comment by whalekeykeeper** [comment]
@duncdrum For those Wikipedia links that successfully return Q-identifiers after querying, can I trust them? Or should they be used to compare with the result of the other approach (query by name)?

**Comment by whalekeykeeper** [comment]
mistakenly clicked the "close" button

**Comment by duncdrum** [comment]
You can trust them

**Comment by whalekeykeeper** [comment]
I have used two different approaches (lookup by name & use the Wikipedia links).
For each, a JSON file is stored with a format: `dictionary[unique_person_id] = [Q-identifier, a_dictionary_of_collected_wikidata_information(name_gender_birthyear_deadthyear_birthplace_if_possible)]`
The length for each is 544 and 385 now. 

I randomly checked some values for some mutual keys, for most, they have the same Q_identifier for the same unique person_id (yeah!!!)
However, there are a few differences. With talking about the difference, the latter approach is more accurate in general (which is very nice).

But rarely, I also found one mutual key in dictionaries that are stored for two approaches that shows something:
```
# Lookup by name
name[key]:  AG0332 
 ['Q326409', {'Q-id': 'Q326409', 'name': 'Jiří Hanzelka', 'gender': 'male', 'birthyear': '1920', 'deathyear': '2003', 'birthplace': 'Štramberk'}]

# Use the Wikipedia links
wikipedia[key]:  AG0332 
 ['Q22011139', {'Q-id': 'Q22011139', 'name': 'Hanzelka and Zikmund'}]
```
For the above example, it might be because the stored Wikipedia link is for not only Hanzelka but also another person Zikmund. 

There are roughly 20~30 mutual keys that show a difference, should I check all of them by hand?

**Comment by duncdrum** [comment]
Let's create another issue about these first, we can let one of the other hiwis check the links and make corrections later.

**Comment by whalekeykeeper** [comment]
okay

**Comment by whalekeykeeper** [comment]
How about I trust all the valid Wikipedia links for now and finish the script of `authenticity_person.py`?

**Comment by whalekeykeeper** [comment]
But it might introduce a few (<32 definitely) mistakes.

```
For person with id  AG0553 :
name[key]:  
 ['Q45676740', {'Q-id': 'Q45676740', 'name': 'Bi Zhang', 'gender': 'male'}]
wikipedia[key]:  
 ['Q10323041', {'Q-id': 'Q10323041', 'name': 'Q10323041'}] 
```

For AG0553, the given wikipedia link is `https://zh.wikipedia.org/wiki/%E6%9B%B9%E5%85%A8%E7%A2%91`. It is about the inscription on a stone.

This kind of mistake can be filtered out after checking the `differences_to_be_checked.txt` by hand. See  #23

**Comment by whalekeykeeper** [comment]
The Longest-match rule will be applied for now.
For conflicting outputs, the one that got more matched features while being compared to the information in Person.csv will be chosen.

**Comment by whalekeykeeper** [comment]
The longest_match rule applied.
So far, for the same person_id, the scores obtained by querying by name and by querying by Wikipedia link are not the same.
For future cases, if two approaches obtain the same score, a manual check is needed.

**Comment by duncdrum** [comment]
with longest match @whalekeykeeper i think this can be closed
