### ISSUE TITLE
Disconnected with the Wikidata endpoint, probably because of too many queries

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/WikidataLookup#22]
Suspects that `time.sleep(sleep)` is not enough.

Got the following error message when running with the full `Person.csv`.
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query.wikidata.org', port=443): 
Max retries exceeded with url: 
...
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef1142e130>: 
Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

```

Plan to divide the whole `Person.csv` into several parts and run them one by one.

**Comment by duncdrum** [comment]
Yes please remember to document what splits you tried. Future uses of the api will likely never go against the same rate limiations as I doubt an update will contain more data in one batch then what we have now

**Comment by whalekeykeeper** [comment]
Currently, we have 627 entries in Person.csv.
The first attempt splits them into 2-person entries to see if the whole script is working in an expected way.
Until the github service shortly broken, the first 424 entries are queried successfully.
Now, further, to experiment with the size of each chunk to see if it can accept ~ 20 person entries at one go.

**Comment by whalekeykeeper** [comment]
Result:
Can't find any match: 83
At least one match and the wiki info are stored: 544

20 as a batch has no problem. Probably can handle a larger size.

**Comment by whalekeykeeper** [comment]
Manually checked the last ten unique person ID in `Person.csv`, i.e. AG0618, AG0619, AG0620, AG0621, AG0622, AG0623, AG0624, AG0625, AG0626, AG1000. From the result, we have the following analysis and summary:
- **Except for AG0623, the matched Wikidata entities are all correct.**
- The matched Wikidata entity of AG623 seems to be not correct. They're different people with the same name.
- Wikidata can be used to correct the death year (2011) for AG1000(the death year 2010).
- Wikidata can be used to correct the birth year for AG0619 and to narrow the death year down from a range for AG0619.
- For AG0619, the birthplace is Hubei in ReadAct and Zigui in Wikidata: Zigui belongs to Hubei.

- The accuracy of this query script seems to be fine.
- The next step is to make use of the Wikipedia link in `Person.csv` and to use the extracted Wikidata information to modify the `Person.csv`.
