### ISSUE TITLE
strategy for searching with only name in the command line tool

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/WikidataLookup#27]
So far, searching with the following combination(s) is implemented in the command line tool:
1. 'person_id' which exists in ReadAct
2.  Wikipedia link
3. Wikidata id

This issue is aiming to discuss about the strategy for searching with only `family_name`, `name_lang`, and `first_name`.

For example, user has given a person entry with only `family_name`,  `first_name`, and `name_lang`, and nothing else, our weighting mechanism wouldn't work if there are no comparable information.
What we can choose are:
1. Require users to input more information in this case
2. Choose the first returned Q-id if we can find any person entities by SPARQL querying with name.

What do you think? @duncdrum

**Comment by whalekeykeeper** [comment]
The current strategy is to return the first found.
See 423bbe0

**Comment by duncdrum** [comment]
Returning the first match seems the way to go, I would however augment `Person.note` with something like "uncertain match"

**Comment by whalekeykeeper** [comment]
Implemented.
