### ISSUE TITLE
Conflict in module importing 

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/WikidataLookup#39]
There is a path/format conflict.
test file needs: `from src.scripts.authenticity_person import ...`
the command line tool needs: `from authenticity_person import ...`
Gonna fix it right now.

**Comment by duncdrum** [comment]
Where do you see those ? I don’t see them in either #34 and not in #38 either.

**Comment by whalekeykeeper** [comment]
when I try to run both locally from command line.

**Comment by duncdrum** [comment]
Try module syntax

**Comment by whalekeykeeper** [comment]
I added a few `__init__.py` to make sure the package to have subpackage structure, then use the module syntax, the problem is gone.
(There is `src/`, I added it.)

**Comment by whalekeykeeper** [comment]
Tests are updated as well. 11 tests passed in at least IDE environment.
The command used locally is `python3.8 -m src.scripts.command_line_tool src/CSV/Person_2.csv`
