### ISSUE TITLE
Instance types of institution entities for SPARQL query

### ISSUE THREAD

**Issue by whalekeykeeper** [readchina/WikidataLookup#48]
Hi @duncdrum 
I am trying to write a SPARQL query to get QIDs by looking up with `Institution` names.
For example, for `Beijing No. 4 High School (Q4881166)`.
I have the following query:
```
SELECT distinct ?in ?inLabel ?inDescription
WHERE{
    {?in wdt:P31 wd:Q4876006;
                rdfs:label "Beijing No. 4 High School"@en}
    UNION
    {?in wdt:P31 wd:Q5962346;
                rdfs:label "Beijing No. 4 High School"@en}
  SERVICE wikibase:label { bd:serviceParam wikibase:language  "[AUTO_LANGUAGE], en"}
}
```

The key makes this query work is `wd:Q4876006`, which represents for `Beacon high schools in Beijing (Q4876006)`. 
I kept the `UNION` statement here because I think the institutions in `Institution.csv` will be referenced to different instance categories so that later I can add similar structures easily.

However, I want to use instance types which can be much more abstract than `Beacon high schools in Beijing (Q4876006)`.
I tried with the parent instance type of `Beacon high schools in Beijing (Q4876006)`, but it doesn't work, the grandparent-like instant type doesn't work as well.

Any hint? I suppose otherwise I can go to read the source code of `wikibaseintegrator` to see how they achieved it.

**Comment by duncdrum** [comment]
Before rolling our own solution, checking how the integrator implements this is a good idea. Top of my head I don’t see an obvious solution / reason why our mismatch rate is substantially higher than theirs.

**Comment by whalekeykeeper** [comment]
My guess is that they used `regex` and we are asking for exact match string. Am checking their implements now.

**Comment by duncdrum** [comment]
yes basically we are happy if most of the name string appears in the wikidata `label`, getting a good formula to implement this in code will require some tweaking

**Comment by whalekeykeeper** [comment]
This will be closed due to the fact that we replaced the SPARQL query of searching strings with MediaWiki API service.
